# Generated by Django 4.2.3 on 2023-07-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_proveedor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='insumo',
            field=models.CharField(max_length=100),
        ),
    ]
