# Generated by Django 4.2.3 on 2023-07-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_detalleordencompra_producto_ordencompra_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='productos',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='archivo',
            field=models.FileField(default=1, upload_to='ordenes_compra_files/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='DetalleOrdenCompra',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
