# Generated by Django 4.2.3 on 2023-07-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_remove_ordencompra_productos_ordencompra_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivos_orden_compra/'),
        ),
    ]
