# Generated by Django 4.2.3 on 2023-07-30 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_alter_ordencompra_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenDeCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20)),
                ('archivo', models.FileField(upload_to='ordenes/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.cliente')),
            ],
        ),
        migrations.DeleteModel(
            name='OrdenCompra',
        ),
    ]
