# Generated by Django 4.2.3 on 2023-07-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_ordendecompra_delete_ordencompra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='archivo',
            field=models.FileField(upload_to='ordenes_compra/'),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='cliente',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='ordendecompra',
            name='numero_orden',
            field=models.CharField(max_length=100),
        ),
    ]
