# Generated by Django 4.2.3 on 2023-07-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_alter_ordendecompra_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='numero_orden',
            field=models.CharField(max_length=50),
        ),
    ]
