# Generated by Django 4.2.3 on 2023-07-30 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0009_alter_ordendecompra_numero_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendecompra',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.cliente'),
        ),
    ]
